### ISSUE TITLE
iswt2

### ISSUE THREAD

**Issue by bamford** [nigma/pywt#1]
First of all, thanks for a very useful module!  I'm very new to wavelets, so please forgive me if this is a stupid question.

Is there a reason there isn't an implementation of iswt and iswt2 in pywt?  I've seen [code for iswt](http://groups.google.com/group/pywavelets/browse_thread/thread/6cd15d85be83e6bd) on the Google Groups discussion, but I really want to quickly try out denoising images with SWT, for which I need an implementation of iswt2.

Any chance that you've got that code somewhere but not yet committed it?!?

**Comment by nachoplus** [comment]
Hello everyone,

pywt is incomplete without iswt(2) implementation. I encourage the author(s) to do it!

Anyway pywt it is a great module. Thanks!

**Comment by rgommers** [comment]
Hi all, this is being worked on by @ThomasA and @aaren in https://github.com/rgommers/pywt/pull/55

It's not yet done; contributions and testing of the code in that branch once completed would be useful.

**Comment by ThomasA** [comment]
I am working on this and will be committing to aaren/pywt on the issue38 branch for inclusion in pull request to @rgommers when ready.

**Comment by rgommers** [comment]
https://github.com/PyWavelets/pywt/issues/57 is an issue on the active repo, so let's keep that open for this enhancement request and close this issue. Thanks all!
