### ISSUE TITLE
How to use scaling parameter in PyWavelet?

### ISSUE THREAD

**Issue by Rajasivaranjan** [nigma/pywt#11]
I'm using wavelet transform for crop phenology detection. In this i'm using Modis ndvi time series (9 months 8-days composite). I want to apply wavelet transform with scale 32. I know to apply wavelet transform. What i want to know is how to give scaling parameter. 

Thanks in advance
Rajasivaranjan

**Comment by rgommers** [comment]
@Rajasivaranjan sorry no one replied to your question yet. This repo isn't really active anymore so not the best place to ask. I suggest the mailing list https://groups.google.com/forum/#!forum/pywavelets and/or StackOverflow, you might have better luck.

**Comment by rgommers** [comment]
Also, some more details may help get a response. For example show the code you have that works and ask how to add scaling to that. That's more concrete and hence easier to answer.
