### ISSUE TITLE
Continuing PyWavelets development on PyPi

### ISSUE THREAD

**Issue by rgommers** [nigma/pywt#13]
Hi @nigma, as you may have seen on my repo the activity has further picked up and we've decided to start creating new releases: https://github.com/rgommers/pywt/issues/61. We're planning on doing a v0.3.0 release which is fully backwards compatible and with Python 3.x support this weekend. And quickly after that a v0.4.0 with more new features and refactoring.

Our question is whether you are okay with giving us (one or more of me, @kwohlfahrt, @grlee77 and @aaren) access to https://pypi.python.org/pypi/PyWavelets so we can put those releases there. That would be friendlier to users than renaming the repo and making it really a fork.

**Comment by rgommers** [comment]
My PyPi username is ``rgommers`` if you'd like to give me access. 

At all: please add your PyPi username here as well if you'd like to get access.

**Comment by rgommers** [comment]
And let me extend the request to ReadTheDocs - would be nice to be able to update that as well. I guess that needs pointing readthedocs to my repo and giving me permissions for pywavelets.readthedocs.org

**Comment by nigma** [comment]
Hi @rgommers, that sounds great and thanks for taking over the development of this project.

I'm more that happy to give you access to PyPI, ReadTheDocs and other resources.

I already sent you an invite to PyPI. Please let me know if you can log in and see the project details there.
I'll need your ReadTheDocs username in order to add you to the maintainers list.

Let me know if there is anyone else I should send invites to.

Is there anything else I can help with? Do you need access to this repository? I was thinking that I should perhaps move it to an organization account as it is still getting a lot of traffic.

**Comment by rgommers** [comment]
@nigma fantastic, thanks! I do have access on PyPi now. The PyPi access also gives access to http://pythonhosted.org/PyWavelets/ it looks like.

For ReadTheDocs my username is also ``rgommers``.

Access to this repo so I can close issues and close/merge PRs may be useful as well. Starting an organization repo is a good idea, however I think it would be better to move my repo to that org rather than yours, because mine already has accumulated a lot more issues and PRs.

**Comment by rgommers** [comment]
There's also http://www.pybytes.com/pywavelets/, which is by now simply a copy of what's on ReadTheDocs and pythonhosted.org. Does it add anything to keep that site? It may be easier to just remove all references to it from the docs....

**Comment by rgommers** [comment]
Got access on ReadTheDocs, thanks @nigma

**Comment by rgommers** [comment]
And got access to this repo as well. Plus you joined the new PyWavelets org. So all set here!

**Comment by rgommers** [comment]
Except for your opinion on http://www.pybytes.com/pywavelets. The Wavelet Browser that is also on that site is nice, but the pywavelets part of the site is a third copy that would be best phased out imho.

**Comment by nigma** [comment]
I'm updating the readme in this project to let the people know about the new home.

Yes, what's left on my side is to update the pybytes.com/pywavelets and redirect to readthedocs. I'd like to put proper redirects there or temporarily upload a copy of the new docs so people visiting the site from google (a couple thousand unique visitors a month) don't get a nasty 404.

We should also clean up some of the wording and highlight the new maintainers in the readme and docs. Please feel free to make any changes as you see suitable.

**Comment by rgommers** [comment]
New repo location: https://github.com/PyWavelets/pywt (10 minutes young).

**Comment by rgommers** [comment]
Proper redirects sounds good to me.

**Comment by rgommers** [comment]
In https://github.com/PyWavelets/pywt/pull/73 I changed the docs and in https://github.com/PyWavelets/pywt/pull/79 I added release notes for v0.3.0 with some explanation of the repo move and history. Will update now for ``rgommers -> PyWavelets`` and then it's pretty much done I think.

**Comment by rgommers** [comment]
Closing this, all done a long time ago.
