### ISSUE TITLE
length of returned arrays

### ISSUE THREAD

**Issue by nareto** [nigma/pywt#15]
why does `pywt.dwt(np.arange(8),'db2')` return two arrays of size 5 each? As far as I understand the DWT should always do a downsampling of size 2, no matter the length of the filter... Am I missing something?

EDIT: sorry, saw the official repo has moved. Maybe it would be best to delete this one?

**Comment by rgommers** [comment]
That may indeed be best. When deleting this repo, https://github.com/PyWavelets/pywt can be chosen as the new main one  (see https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository)

@nigma if you agree, could you do this?
