### ISSUE TITLE
Compilation issue (Cython) : probable solution.

### ISSUE THREAD

**Issue by gd2shoe** [nigma/pywt#2]
As I understand it, Cython went through a change recently.  Pywt no longer compiles with the latest Cython unless  "src/_pywt.pyx" changes __new__ to __cinit__.

Now, I don't know Cython well enough myself to know this for myself.  I just know that another project "https://code.google.com/p/pyffmpeg/issues/detail?id=44" comment #3 stated flatly that this change needs to take place, and pywt compiles after I make the change.

Using updated cygwin, with "pip" updated Cython.

**Comment by rgommers** [comment]
Cython issues are all resolved in master branch of https://github.com/PyWavelets/pywt, so closing this issue.
