### ISSUE TITLE
no version information available at runtime

### ISSUE THREAD

**Issue by hayne** [nigma/pywt#5]
There doesn't seem to be any way to get information about what version of pywt is in use at runtime.
The usual way to get version information from a module is via a module attribute '__version__' but there is no such attribute for pywt.

BTW, the reason why I need this is because I am writing a super-installer that installs several modules (including pywt) for use with an application and I want to find out if the user already has the desired version of pywt installed.
Previously, I was creating my own version of pywt and I edited the file "__init__.py" in the 'pywt' sub-folder of the 'src' folder and added the following line near the top:
version = '0.2.0'
But now that I am using the supplied Windows installer, I can't do this.

**Comment by rgommers** [comment]
`__version__` attribute and `pywt.version` autogenerated module available in master branch and upcoming v0.3.0 of https://github.com/PyWavelets/pywt, so closing this issue.
