### ISSUE TITLE
Links to github do not work

### ISSUE THREAD

**Issue by LunarLanding** [nigma/pywt#9]
For instance:
When at http://pywavelets.readthedocs.org/en/latest/ref/idwt-inverse-discrete-wavelet-transform.html?highlight=waverec#pywt.waverec if i click the left tab link below edit this document, and then the link for supposedly the source code for the transform, it takes me to https://github.com/nigma/pywt/blob/develop/doc/source/ref/idwt-inverse-discrete-wavelet-transform.rst instead.

**Comment by rgommers** [comment]
This indeed doesn't work, needs double checking after v0.3.0 docs are uploaded.

**Comment by rgommers** [comment]
Fixed now in the master branch of https://github.com/PyWavelets/pywt and on ReadTheDocs ('latest' doc version, and will be in v0.4.0 also).

Thanks for the report @LunarLanding
